### ISSUE TITLE
[Design review] Improve rich text editor UI

### ISSUE THREAD

**Issue by jonnyandrew** [vector-im/element-x-android#1315]
## Summary

Issues raised during design review of the rich text editor:

## Scope

```[tasklist]
### Tasks
- [x] Update design of editor UI ([Figma design](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=11197-76744&mode=design&t=l2mP7SMYOZ1NqE9W-0)) https://github.com/vector-im/element-x-android/pull/1332
- [x] - Update send icon and edit icon https://github.com/vector-im/element-x-android/pull/1332
- [x] - Update formatting icons (pending SVGs) https://github.com/vector-im/element-x-android/pull/1332
- [x] Editor corner radius should not change when text falls onto multiple lines https://github.com/vector-im/element-x-android/pull/1332
- [x] "Text formatting" option is not fully visible in composer options menu https://github.com/vector-im/element-x-android/pull/1335
- [x] Pressing text formatting option should open keyboard https://github.com/vector-im/element-x-android/pull/1337
- [x] Check the correct dialog is displayed when setting link on highlighted text https://github.com/vector-im/element-x-android/pull/1332
- [x] Spacing above/below text is different when displaying multiple lines vs a single line https://github.com/vector-im/element-x-android/pull/1332
- [x] Truncate message placeholder https://github.com/vector-im/element-x-android/pull/1347
- [x] - Allow RTE link color and code background to be customised https://github.com/matrix-org/matrix-rich-text-editor/pull/813
- [x] Use design system color for links https://github.com/vector-im/element-x-android/pull/1362
- [x] Update color and font of code and inline code ([Figma design](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=9782-52062&mode=dev)) https://github.com/vector-im/element-x-android/pull/1362
```
# Sign-off

- [x] Design sign-off on completion
  - [ ] @callumu noted that corner radius is still not correct
- [x] QA sign-off on completion
- [x] Product sign-off on completion

##  Stretch goals
None at this time

## Out of scope
-
