### ISSUE TITLE
[Story] Help improve Element by sending analytics data

### ISSUE THREAD

**Issue by yostyle** [vector-im/element-x-android#255]
As a product team member I would like to have insights into users' behavior so that we better cater to their needs.
This feature will not be enable by default. The users will free to enable it in settings if they want.

## Scope
```[tasklist]
### Tasks
- [ ] Begin adding the Analytics class from EA
- [x] Add Analytics UI
- [x] ~~Don't attempt to identify until the SDK has up-to-date account data.~~
- [ ] https://github.com/vector-im/element-x-android/issues/535
- [ ] https://github.com/vector-im/element-x-android/issues/317
- [x] Reset when signing out (It would be actually a per session tracking).
- [x] Ideally, we should stop syncing the source code with the plan (as it's done in Element Android), but rather let the analytics project https://github.com/matrix-org/matrix-analytics-events build and publish a versioned library that EAx will depend on.
```
## Policy

- We **don't** record or profile any account data
- We **don't** share information with third parties
- You can turn off anytime in settings

https://element.io/cookie-policy

###
Settings | Feature
---|---
|![Screenshot_20230330-104130](https://user-images.githubusercontent.com/1191674/228780866-e19ef53f-2fe7-42b9-9771-5bed281101e8.png)|![Screenshot_20230330-104205](https://user-images.githubusercontent.com/1191674/228780891-66150f22-e8cf-4765-8f8b-b42ace9abbd7.png)|

**Comment by giomfo** [comment]
@bmarty can you please update the description to add your request "stop syncing the source code with the plan, but rather let the analytics project https://github.com/matrix-org/matrix-analytics-events build and publish a versioned library that EAx will depend on"

**Comment by yostyle** [comment]
> We must learn not to invade the lives of others for the sole purpose of satisfying one’s own need: the description of this tool is definitely harmful to the privacy of other people.
> 
> I want a world built around people’s freedom. If the purpose of this messenger is to track its users it can say so openly.
> 
> If this thing passes, I’ll switch messenger.

This feature will not be enable by default. The users will free to enable it in settings if they want as it is already the case in Element Android.
We don't want to collect information without the knowledge of users.

**Comment by yostyle** [comment]
> > > We must learn not to invade the lives of others for the sole purpose of satisfying one’s own need: the description of this tool is definitely harmful to the privacy of other people.
> > > I want a world built around people’s freedom. If the purpose of this messenger is to track its users it can say so openly.
> > > If this thing passes, I’ll switch messenger.
> > 
> > 
> > This feature will not be enable by default. The users will free to enable it in settings if they want as it is already the case in Element Android. We don't want to collect information without the knowledge of users.
> 
> Some employer could get that permission with blackmail.
> 
> You’re favoring potentially unfair behavior. And everyone who’s worked as an employee knows what I’m talking about.

Thanks for your feedback. We will be especially careful on this point.
To protect the users :

- We don't record or profile any account data
- We don't share information with third parties

**Comment by yostyle** [comment]
All tasks have been done except [this one](https://github.com/vector-im/element-x-android/issues/535)
